version: '3.7'

services:
  airbyte:
    image: airbyte/airbyte:latest
    ports:
      - "8000:8000"

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: airbyte
      MYSQL_USER: user
      MYSQL_PASSWORD: example
    ports:
      - "3306:3306"
